// <auto-generated> by tools/blocks/generate.py from the prototype; edit by hand from now on. </auto-generated>
namespace KieliWeb.Setup;

public static partial class BlockRegistry
{
	public static readonly (string Key, string Title)[] Pages =
	{
		("site", "Барлық беттер (тақырып, футер, байланыс)"),
		("home", "Басты бет"),
		("author", "Автор"),
		("services", "Қызметтер"),
		("news", "Жаңалықтар мен мақалалар"),
		("kazakhstan", "Қазақстан"),
		("kaztest", "ҚАЗТЕСТ"),
	};

	private static readonly BlockDef[] Defined =
	{
		new BlockDef("site.brand", "site", "Логотип және атау", null, new[]
		{
			new FieldDef("name", "Сайт атауы (логотип жанында)", FieldKind.Text) { NoTranslate = true },
			new FieldDef("logo", "Логотип (SVG не PNG, шаршы)", FieldKind.Image),
			new FieldDef("footerText", "Футердегі қысқа сипаттама", FieldKind.Textarea)
		}),
		new BlockDef("site.nav", "site", "Негізгі мәзір", null, new[]
		{
			new FieldDef("items", "Мәзір тармақтары", FieldKind.List) { Fields = new[]
			{
				new FieldDef("label", "Атауы", FieldKind.Text),
				new FieldDef("url", "Сілтеме", FieldKind.Url),
				new FieldDef("note", "Мобильді мәзірдегі қосымша жазу", FieldKind.Text),
				new FieldDef("key", "Белгі (белсенді бетті көрсету үшін: author, services, kaztest, articles, kazakhstan)", FieldKind.Text) { NoTranslate = true }
			} }
		}),
		new BlockDef("site.contact", "site", "Байланыс деректері", "Бұл деректер тақырыпта, футерде, «Кеңес алу» терезесінде және байланыс бөлімінде бірден өзгереді.", new[]
		{
			new FieldDef("phone", "Телефон (көрінетін түрі)", FieldKind.Text) { NoTranslate = true },
			new FieldDef("whatsapp", "WhatsApp нөмірі (тек цифр, мыс. 77000000000)", FieldKind.Text) { NoTranslate = true },
			new FieldDef("telegram", "Telegram (@ белгісінсіз)", FieldKind.Text) { NoTranslate = true },
			new FieldDef("wechat", "WeChat ID", FieldKind.Text) { NoTranslate = true },
			new FieldDef("wechatQr", "WeChat QR-коды", FieldKind.Image),
			new FieldDef("email", "Электрондық пошта", FieldKind.Text) { NoTranslate = true },
			new FieldDef("address", "Кеңсе мекенжайы", FieldKind.Text),
			new FieldDef("hours", "Жұмыс уақыты (футерде)", FieldKind.Text),
			new FieldDef("timeNote", "Уақыт айырмасы туралы жазу", FieldKind.Text),
			new FieldDef("legalName", "Заңды атауы (футер)", FieldKind.Text),
			new FieldDef("bin", "БСН", FieldKind.Text) { NoTranslate = true }
		}),
		new BlockDef("site.social", "site", "Әлеуметтік желілер", "WeChat батырмасы әрқашан «Кеңес алу» терезесін ашады, оны мұнда қосудың қажеті жоқ.", new[]
		{
			new FieldDef("items", "Желілер", FieldKind.List) { Fields = new[]
			{
				new FieldDef("icon", "Белгіше", FieldKind.Icon),
				new FieldDef("label", "Атауы", FieldKind.Text) { NoTranslate = true },
				new FieldDef("url", "Сілтеме", FieldKind.Url)
			} }
		}),
		new BlockDef("site.footer", "site", "Футер", null, new[]
		{
			new FieldDef("col1Title", "1-баған тақырыбы", FieldKind.Text),
			new FieldDef("col1Links", "1-баған сілтемелері", FieldKind.List) { Fields = new[]
			{
				new FieldDef("label", "Атауы", FieldKind.Text),
				new FieldDef("url", "Сілтеме", FieldKind.Url)
			} },
			new FieldDef("col2Title", "2-баған тақырыбы", FieldKind.Text),
			new FieldDef("col2Links", "2-баған сілтемелері", FieldKind.List) { Fields = new[]
			{
				new FieldDef("label", "Атауы", FieldKind.Text),
				new FieldDef("url", "Сілтеме", FieldKind.Url)
			} },
			new FieldDef("col3Title", "Байланыс бағанының тақырыбы", FieldKind.Text),
			new FieldDef("copyright", "Төменгі жол (© жылы өзі қойылады)", FieldKind.Html),
			new FieldDef("credit", "Әзірлеуші: логотип алдындағы жазу", FieldKind.Text),
			new FieldDef("creditUrl", "Әзірлеушінің сайты (логотиптің сілтемесі)", FieldKind.Url)
		}),
		new BlockDef("site.consult", "site", "«Кеңес алу» терезесі", null, new[]
		{
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("lead", "Түсініктеме", FieldKind.Html),
			new FieldDef("pickHint", "Өтінім коды туралы кеңес", FieldKind.Text),
			new FieldDef("wechatHint", "WeChat туралы ескерту", FieldKind.Html),
			new FieldDef("separator", "Бөлгіш жазу", FieldKind.Text),
			new FieldDef("msgPlaceholder", "«Жағдайыңыз» өрісіндегі мысал", FieldKind.Textarea),
			new FieldDef("consent", "Келісім мәтіні", FieldKind.Text),
			new FieldDef("submit", "Жіберу батырмасы", FieldKind.Text),
			new FieldDef("doneText", "Жіберілгеннен кейінгі мәтін", FieldKind.Textarea),
			new FieldDef("fab", "Экран бұрышындағы батырма", FieldKind.Text)
		}),
		new BlockDef("seo.home", "home", "SEO: браузер тақырыбы мен сипаттама", null, new[]
		{
			new FieldDef("title", "Бет тақырыбы (браузерде)", FieldKind.Text),
			new FieldDef("description", "Сипаттама (іздеу жүйелері үшін)", FieldKind.Textarea),
			new FieldDef("image", "Бөлісу суреті (og:image)", FieldKind.Image)
		}),
		new BlockDef("home.hero", "home", "Бірінші экран (автор)", null, new[]
		{
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("name", "Аты-жөні (әр жол жаңа жолда)", FieldKind.Lines),
			new FieldDef("role", "Лауазымы", FieldKind.Text),
			new FieldDef("slogan", "Ұран", FieldKind.Text),
			new FieldDef("lead", "Қысқа мәтін", FieldKind.Textarea),
			new FieldDef("ctaConsult", "«Кеңес алу» батырмасы", FieldKind.Text),
			new FieldDef("ctaServices", "Қызметтер батырмасы", FieldKind.Text),
			new FieldDef("ctaAuthor", "Автор сілтемесі", FieldKind.Text),
			new FieldDef("photo", "Фото (фоны мөлдір PNG/WebP, 4:5)", FieldKind.Image),
			new FieldDef("photoAlt", "Фото сипаттамасы", FieldKind.Text),
			new FieldDef("city", "Фондағы қала суреті", FieldKind.Image)
		}),
		new BlockDef("home.strip", "home", "Үш артықшылық жолағы", null, new[]
		{
			new FieldDef("items", "Элементтер", FieldKind.List) { Fields = new[]
			{
				new FieldDef("icon", "Белгіше", FieldKind.Icon),
				new FieldDef("title", "Тақырып (HTML рұқсат)", FieldKind.Text),
				new FieldDef("text", "Түсініктеме", FieldKind.Text)
			} }
		}),
		new BlockDef("home.help", "home", "«Сізге қандай көмек керек?» тақырыбы", "Қызмет бөлімдері мен түрлері «Қызметтер» мәзірінде өзгертіледі.", new[]
		{
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("lead", "Түсініктеме", FieldKind.Textarea),
			new FieldDef("foot", "Төменгі жол", FieldKind.Html)
		}),
		new BlockDef("home.kaztest", "home", "ҚАЗТЕСТ жарнама блогы", null, new[]
		{
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("lead", "Мәтін", FieldKind.Textarea),
			new FieldDef("facts", "Сандар", FieldKind.List) { Fields = new[]
			{
				new FieldDef("value", "Мән", FieldKind.Text),
				new FieldDef("label", "Жазу", FieldKind.Text)
			} },
			new FieldDef("ctaStart", "Негізгі батырма", FieldKind.Text),
			new FieldDef("ctaMore", "Сілтеме мәтіні", FieldKind.Text),
			new FieldDef("mockVariant", "Үлгі: нұсқа", FieldKind.Text) { NoTranslate = true },
			new FieldDef("mockSection", "Үлгі: бөлім", FieldKind.Text) { NoTranslate = true },
			new FieldDef("mockTimer", "Үлгі: таймер", FieldKind.Text) { NoTranslate = true },
			new FieldDef("mockKicker", "Үлгі: тапсырма", FieldKind.Text) { NoTranslate = true },
			new FieldDef("mockQuestion", "Үлгі: сұрақ", FieldKind.Text) { NoTranslate = true },
			new FieldDef("mockOptions", "Үлгі: жауаптар", FieldKind.List) { Fields = new[]
			{
				new FieldDef("text", "Жауап", FieldKind.Text) { NoTranslate = true }
			} },
			new FieldDef("mockSelected", "Үлгі: таңдалған жауап (1–4)", FieldKind.Number)
		}),
		new BlockDef("home.route", "home", "«Түсінікті қадамдар»", null, new[]
		{
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("aside", "Оң жақтағы түсініктеме", FieldKind.Textarea),
			new FieldDef("steps", "Қадамдар", FieldKind.List) { Fields = new[]
			{
				new FieldDef("title", "Атауы", FieldKind.Text),
				new FieldDef("text", "Түсініктеме", FieldKind.Textarea)
			} }
		}),
		new BlockDef("home.posts", "home", "Жаңалықтар бөлімі", "Мақалалардың өзі «Жаңалықтар» мәзірінде. Басты бетте «Маңызды» белгісі бар және ең жаңа мақалалар шығады.", new[]
		{
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("aside", "Оң жақтағы түсініктеме", FieldKind.Textarea),
			new FieldDef("moreText", "«Толығырақ» батырмасы", FieldKind.Text),
			new FieldDef("moreNote", "Батырма жанындағы жазу", FieldKind.Text)
		}),
		new BlockDef("home.kazakhstan", "home", "«Қазақстанды танып-біліңіз» бөлімі", null, new[]
		{
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("aside", "Оң жақтағы түсініктеме", FieldKind.Textarea),
			new FieldDef("linkText", "Сілтеме мәтіні", FieldKind.Text),
			new FieldDef("linkUrl", "Сілтеме", FieldKind.Url),
			new FieldDef("tabs", "Қойындылар", FieldKind.List) { Fields = new[]
			{
				new FieldDef("label", "Атауы", FieldKind.Text),
				new FieldDef("kind", "Түрі", FieldKind.Select) { Options = new[] { ("places", "Нысандар"), ("heritage", "Мәдени мұра") } },
				new FieldDef("items", "Нысандар (әр жолға бір: нысанның сілтеме белгісі не мұраның қазақша атауы)", FieldKind.Textarea) { NoTranslate = true }
			} }
		}),
		new BlockDef("home.faq", "home", "Сұрақ-жауап", null, new[]
		{
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("lead", "Түсініктеме", FieldKind.Text),
			new FieldDef("items", "Сұрақтар", FieldKind.List) { Fields = new[]
			{
				new FieldDef("q", "Сұрақ", FieldKind.Text),
				new FieldDef("a", "Жауап (HTML рұқсат)", FieldKind.Textarea)
			} }
		}),
		new BlockDef("home.contact", "home", "Байланыс бөлімі (соңғы)", null, new[]
		{
			new FieldDef("image", "Фон суреті", FieldKind.Image),
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("lead", "Мәтін", FieldKind.Textarea),
			new FieldDef("wechatLabel", "WeChat жазуы", FieldKind.Text),
			new FieldDef("formTitle", "Өтінім формасының тақырыбы", FieldKind.Text),
			new FieldDef("formLead", "Форма түсініктемесі", FieldKind.Text),
			new FieldDef("doneText", "Жіберілгеннен кейінгі мәтін", FieldKind.Text)
		}),
		new BlockDef("seo.author", "author", "SEO: браузер тақырыбы мен сипаттама", null, new[]
		{
			new FieldDef("title", "Бет тақырыбы (браузерде)", FieldKind.Text),
			new FieldDef("description", "Сипаттама (іздеу жүйелері үшін)", FieldKind.Textarea),
			new FieldDef("image", "Бөлісу суреті (og:image)", FieldKind.Image)
		}),
		new BlockDef("author.hero", "author", "Бірінші экран", null, new[]
		{
			new FieldDef("photo", "Фото (фоны мөлдір, 4:5)", FieldKind.Image),
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("name", "Аты-жөні", FieldKind.Text),
			new FieldDef("role", "Лауазымы", FieldKind.Textarea),
			new FieldDef("lead", "Кіріспе", FieldKind.Textarea),
			new FieldDef("quoteLabel", "Ұстаным белгісі", FieldKind.Text),
			new FieldDef("quote", "Ұстаным", FieldKind.Text),
			new FieldDef("stats", "Көрсеткіштер", FieldKind.List) { Fields = new[]
			{
				new FieldDef("label", "Атауы", FieldKind.Text),
				new FieldDef("value", "Мәні", FieldKind.Text),
				new FieldDef("small", "Қосымша жазу", FieldKind.Text)
			} },
			new FieldDef("ctaConsult", "«Кеңес алу» батырмасы", FieldKind.Text),
			new FieldDef("linkText", "Екінші батырма", FieldKind.Text),
			new FieldDef("linkUrl", "Екінші батырма сілтемесі", FieldKind.Url)
		}),
		new BlockDef("author.social", "author", "Қоғамдық жұмыс", null, new[]
		{
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("lead", "Кіріспе", FieldKind.Textarea),
			new FieldDef("issues", "Көтеріп жүрген мәселелері", FieldKind.List) { Fields = new[]
			{
				new FieldDef("icon", "Белгіше", FieldKind.Icon),
				new FieldDef("text", "Мәтін", FieldKind.Text)
			} },
			new FieldDef("body", "Негізгі мәтін", FieldKind.Html)
		}),
		new BlockDef("author.stage", "author", "Би өнері (қара фон)", null, new[]
		{
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("lead", "Мәтін", FieldKind.Textarea),
			new FieldDef("studioLabel", "Студия белгісі", FieldKind.Text),
			new FieldDef("studioName", "Студия атауы", FieldKind.Text),
			new FieldDef("studioText", "Студия туралы", FieldKind.Textarea),
			new FieldDef("groupsTitle", "Би топтары тақырыбы", FieldKind.Text),
			new FieldDef("groups", "Би топтары", FieldKind.List) { Fields = new[]
			{
				new FieldDef("name", "Атауы", FieldKind.Text)
			} },
			new FieldDef("groupsNote", "Топтар туралы", FieldKind.Textarea),
			new FieldDef("projectsTitle", "Жобалар тақырыбы", FieldKind.Text),
			new FieldDef("projects", "Жобалар", FieldKind.List) { Fields = new[]
			{
				new FieldDef("name", "Атауы", FieldKind.Text)
			} },
			new FieldDef("projectsNote", "Жобалар туралы", FieldKind.Textarea)
		}),
		new BlockDef("author.business", "author", "Кәсіпкерлік және компания", null, new[]
		{
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("lead", "Мәтін", FieldKind.Textarea),
			new FieldDef("cardLabel", "Карточка белгісі", FieldKind.Text),
			new FieldDef("cardName", "Компания атауы", FieldKind.Text),
			new FieldDef("cardSmall", "Ұйымдық-құқықтық нысаны", FieldKind.Text),
			new FieldDef("cardText", "Компания туралы", FieldKind.Textarea),
			new FieldDef("dirs", "Қызмет бағыттары", FieldKind.List) { Fields = new[]
			{
				new FieldDef("name", "Атауы", FieldKind.Text)
			} },
			new FieldDef("cardNote", "Қорытынды", FieldKind.Textarea),
			new FieldDef("linkText", "Сілтеме мәтіні", FieldKind.Text),
			new FieldDef("linkUrl", "Сілтеме", FieldKind.Url)
		}),
		new BlockDef("author.goals", "author", "Бастамаларының өзегі", null, new[]
		{
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("lead", "Мәтін", FieldKind.Textarea),
			new FieldDef("items", "Мақсаттар", FieldKind.List) { Fields = new[]
			{
				new FieldDef("text", "Мәтін", FieldKind.Text)
			} }
		}),
		new BlockDef("author.project", "author", "«Киелі» жобасы", null, new[]
		{
			new FieldDef("image", "Сурет", FieldKind.Image),
			new FieldDef("imageAlt", "Сурет сипаттамасы", FieldKind.Text),
			new FieldDef("caption", "Сурет астындағы жазу", FieldKind.Text),
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("lead", "Мәтін", FieldKind.Textarea),
			new FieldDef("bullets", "Тізім", FieldKind.List) { Fields = new[]
			{
				new FieldDef("text", "Мәтін", FieldKind.Text)
			} },
			new FieldDef("linkText", "Сілтеме мәтіні", FieldKind.Text),
			new FieldDef("linkUrl", "Сілтеме", FieldKind.Url)
		}),
		new BlockDef("author.path", "author", "Автордың жолы (дәйексөз)", null, new[]
		{
			new FieldDef("lines", "Жолдар", FieldKind.List) { Fields = new[]
			{
				new FieldDef("text", "Мәтін", FieldKind.Text)
			} },
			new FieldDef("final", "Қорытынды жол", FieldKind.Textarea)
		}),
		new BlockDef("author.articles", "author", "Пайдалы нұсқаулықтар", "Жаңалықтар бөлімінен автор аты жазылған ең соңғы мақалалар шығады.", new[]
		{
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("linkText", "Сілтеме мәтіні", FieldKind.Text),
			new FieldDef("count", "Қанша мақала көрсету", FieldKind.Number)
		}),
		new BlockDef("author.cross", "author", "Төменгі шақыру жолағы", null, new[]
		{
			new FieldDef("image", "Фон суреті", FieldKind.Image),
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("text", "Мәтін", FieldKind.Textarea),
			new FieldDef("button", "Негізгі батырма («Кеңес алу» терезесін ашады)", FieldKind.Text),
			new FieldDef("serviceKey", "Терезеде таңдалып тұратын қызмет (бос болса — жалпы кеңес)", FieldKind.Service),
			new FieldDef("linkText", "Екінші батырма мәтіні", FieldKind.Text),
			new FieldDef("linkUrl", "Екінші батырма сілтемесі", FieldKind.Url)
		}),
		new BlockDef("seo.services", "services", "SEO: браузер тақырыбы мен сипаттама", null, new[]
		{
			new FieldDef("title", "Бет тақырыбы (браузерде)", FieldKind.Text),
			new FieldDef("description", "Сипаттама (іздеу жүйелері үшін)", FieldKind.Textarea),
			new FieldDef("image", "Бөлісу суреті (og:image)", FieldKind.Image)
		}),
		new BlockDef("services.hero", "services", "Бет басы", null, new[]
		{
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("lead", "Мәтін", FieldKind.Textarea),
			new FieldDef("trust", "Сенім белгілері", FieldKind.List) { Fields = new[]
			{
				new FieldDef("icon", "Белгіше", FieldKind.Icon),
				new FieldDef("text", "Мәтін", FieldKind.Text)
			} },
			new FieldDef("provider", "Қызмет көрсетуші жолы", FieldKind.Html),
			new FieldDef("cta", "Батырма", FieldKind.Text),
			new FieldDef("ctaNote", "Батырма астындағы жазу", FieldKind.Text),
			new FieldDef("image", "Кең сурет", FieldKind.Image),
			new FieldDef("imageAlt", "Сурет сипаттамасы", FieldKind.Text)
		}),
		new BlockDef("services.help", "services", "«Сізге қандай көмек керек?» тақырыбы", null, new[]
		{
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("lead", "Түсініктеме", FieldKind.Textarea),
			new FieldDef("foot", "Төменгі жол", FieldKind.Html)
		}),
		new BlockDef("services.company", "services", "«BASTAU LINE» ЖШС (қара фон)", null, new[]
		{
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("tagline", "Ұран", FieldKind.Text),
			new FieldDef("lead", "Мәтін", FieldKind.Textarea),
			new FieldDef("bridgeLeft", "Көпір: сол жақ", FieldKind.Text),
			new FieldDef("bridgeRight", "Көпір: оң жақ", FieldKind.Text),
			new FieldDef("bridgeLangs", "Көпір: тілдер", FieldKind.Html),
			new FieldDef("address", "Мекенжай", FieldKind.Text),
			new FieldDef("whyTitle", "«Неліктен» тақырыбы", FieldKind.Text),
			new FieldDef("why", "Артықшылықтар", FieldKind.List) { Fields = new[]
			{
				new FieldDef("text", "Мәтін", FieldKind.Text)
			} },
			new FieldDef("motto", "Ұстаным сөздері", FieldKind.List) { Fields = new[]
			{
				new FieldDef("word", "Сөз", FieldKind.Text)
			} }
		}),
		new BlockDef("services.compare", "services", "Салыстыру кестесі", null, new[]
		{
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("aside", "Оң жақтағы түсініктеме", FieldKind.Textarea),
			new FieldDef("table", "Кесте", FieldKind.Html),
			new FieldDef("note", "Кесте астындағы ескерту", FieldKind.Textarea)
		}),
		new BlockDef("services.faq", "services", "Сұрақ-жауап", null, new[]
		{
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("lead", "Түсініктеме", FieldKind.Text),
			new FieldDef("items", "Сұрақтар", FieldKind.List) { Fields = new[]
			{
				new FieldDef("q", "Сұрақ", FieldKind.Text),
				new FieldDef("a", "Жауап (HTML рұқсат)", FieldKind.Textarea)
			} }
		}),
		new BlockDef("services.cross", "services", "Төменгі шақыру жолағы", null, new[]
		{
			new FieldDef("image", "Фон суреті", FieldKind.Image),
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("text", "Мәтін", FieldKind.Textarea),
			new FieldDef("button", "Негізгі батырма («Кеңес алу» терезесін ашады)", FieldKind.Text),
			new FieldDef("serviceKey", "Терезеде таңдалып тұратын қызмет (бос болса — жалпы кеңес)", FieldKind.Service),
			new FieldDef("linkText", "Екінші батырма мәтіні", FieldKind.Text),
			new FieldDef("linkUrl", "Екінші батырма сілтемесі", FieldKind.Url)
		}),
		new BlockDef("seo.news", "news", "SEO: браузер тақырыбы мен сипаттама", null, new[]
		{
			new FieldDef("title", "Бет тақырыбы (браузерде)", FieldKind.Text),
			new FieldDef("description", "Сипаттама (іздеу жүйелері үшін)", FieldKind.Textarea),
			new FieldDef("image", "Бөлісу суреті (og:image)", FieldKind.Image)
		}),
		new BlockDef("news.head", "news", "Бет басы", null, new[]
		{
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("lead", "Мәтін", FieldKind.Textarea),
			new FieldDef("cta", "Батырма", FieldKind.Text),
			new FieldDef("ctaNote", "Батырма астындағы жазу", FieldKind.Text),
			new FieldDef("searchPlaceholder", "Іздеу өрісіндегі мысал", FieldKind.Text),
			new FieldDef("note", "Тізім астындағы жазу", FieldKind.Textarea)
		}),
		new BlockDef("news.cross", "news", "Төменгі шақыру жолағы", null, new[]
		{
			new FieldDef("image", "Фон суреті", FieldKind.Image),
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("text", "Мәтін", FieldKind.Textarea),
			new FieldDef("button", "Негізгі батырма («Кеңес алу» терезесін ашады)", FieldKind.Text),
			new FieldDef("serviceKey", "Терезеде таңдалып тұратын қызмет (бос болса — жалпы кеңес)", FieldKind.Service),
			new FieldDef("linkText", "Екінші батырма мәтіні", FieldKind.Text),
			new FieldDef("linkUrl", "Екінші батырма сілтемесі", FieldKind.Url)
		}),
		new BlockDef("article.author", "news", "Мақала: автор блогы", "Мақалада «Автор» өрісі толтырылса, осы блок мақала соңында және басында шығады.", new[]
		{
			new FieldDef("photo", "Автор фотосы (шаршы)", FieldKind.Image),
			new FieldDef("name", "Аты-жөні", FieldKind.Text),
			new FieldDef("org", "Ұйым", FieldKind.Text),
			new FieldDef("bio", "Қысқа өмірбаяны", FieldKind.Textarea),
			new FieldDef("linkText", "Сілтеме мәтіні", FieldKind.Text),
			new FieldDef("linkUrl", "Сілтеме", FieldKind.Url)
		}),
		new BlockDef("article.aside", "news", "Мақала: оң жақ бағаналар", null, new[]
		{
			new FieldDef("tocTitle", "«Мазмұны» тақырыбы", FieldKind.Text),
			new FieldDef("ctaEyebrow", "Шақыру: үстіңгі жол", FieldKind.Text),
			new FieldDef("ctaText", "Шақыру: мәтін", FieldKind.Textarea),
			new FieldDef("ctaButton", "Шақыру: батырма", FieldKind.Text),
			new FieldDef("shareTitle", "«Бөлісу» тақырыбы", FieldKind.Text),
			new FieldDef("moreEyebrow", "«Тағы оқыңыз»: үстіңгі жол", FieldKind.Text),
			new FieldDef("moreTitle", "«Тағы оқыңыз»: тақырып", FieldKind.Text)
		}),
		new BlockDef("seo.kazakhstan", "kazakhstan", "SEO: браузер тақырыбы мен сипаттама", null, new[]
		{
			new FieldDef("title", "Бет тақырыбы (браузерде)", FieldKind.Text),
			new FieldDef("description", "Сипаттама (іздеу жүйелері үшін)", FieldKind.Textarea),
			new FieldDef("image", "Бөлісу суреті (og:image)", FieldKind.Image)
		}),
		new BlockDef("kazakhstan.head", "kazakhstan", "Бет басы", null, new[]
		{
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("lead", "Мәтін", FieldKind.Textarea),
			new FieldDef("figures", "Сандар", FieldKind.List) { Fields = new[]
			{
				new FieldDef("value", "Мән", FieldKind.Text),
				new FieldDef("label", "Жазу", FieldKind.Text)
			} },
			new FieldDef("epigraph", "Эпиграф", FieldKind.Textarea),
			new FieldDef("epigraphCite", "Эпиграф авторы", FieldKind.Text)
		}),
		new BlockDef("kazakhstan.atlas", "kazakhstan", "Карта бөлімі", null, new[]
		{
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("aside", "Оң жақтағы түсініктеме", FieldKind.Textarea),
			new FieldDef("allRegions", "«Барлық өңір» батырмасы", FieldKind.Text)
		}),
		new BlockDef("kazakhstan.heritage", "kazakhstan", "Мәдени мұра бөлімі", null, new[]
		{
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("aside", "Оң жақтағы түсініктеме", FieldKind.Textarea)
		}),
		new BlockDef("kazakhstan.cross", "kazakhstan", "Төменгі шақыру жолағы", null, new[]
		{
			new FieldDef("image", "Фон суреті", FieldKind.Image),
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("text", "Мәтін", FieldKind.Textarea),
			new FieldDef("button", "Негізгі батырма («Кеңес алу» терезесін ашады)", FieldKind.Text),
			new FieldDef("serviceKey", "Терезеде таңдалып тұратын қызмет (бос болса — жалпы кеңес)", FieldKind.Service),
			new FieldDef("linkText", "Екінші батырма мәтіні", FieldKind.Text),
			new FieldDef("linkUrl", "Екінші батырма сілтемесі", FieldKind.Url)
		}),
		new BlockDef("place.aside", "kazakhstan", "Нысан беті: оң жақ бағаналар", null, new[]
		{
			new FieldDef("aboutTitle", "«Нысан туралы» тақырыбы", FieldKind.Text),
			new FieldDef("panoText", "360° батырмасы", FieldKind.Text),
			new FieldDef("shareTitle", "«Бөлісу» тақырыбы", FieldKind.Text),
			new FieldDef("shareNote", "WeChat туралы ескерту", FieldKind.Text),
			new FieldDef("ctaEyebrow", "Шақыру: үстіңгі жол", FieldKind.Text),
			new FieldDef("ctaText", "Шақыру: мәтін", FieldKind.Textarea),
			new FieldDef("ctaButton", "Шақыру: батырма", FieldKind.Text),
			new FieldDef("relatedEyebrow", "Ұқсас нысандар: үстіңгі жол", FieldKind.Text),
			new FieldDef("relatedTitle", "Ұқсас нысандар: тақырып", FieldKind.Text),
			new FieldDef("relatedLink", "Ұқсас нысандар: сілтеме мәтіні", FieldKind.Text),
			new FieldDef("panoNote", "360° терезесіндегі ескерту", FieldKind.Textarea)
		}),
		new BlockDef("seo.kaztest", "kaztest", "SEO: браузер тақырыбы мен сипаттама", null, new[]
		{
			new FieldDef("title", "Бет тақырыбы (браузерде)", FieldKind.Text),
			new FieldDef("description", "Сипаттама (іздеу жүйелері үшін)", FieldKind.Textarea),
			new FieldDef("image", "Бөлісу суреті (og:image)", FieldKind.Image)
		}),
		new BlockDef("kaztest.head", "kaztest", "Бет басы", null, new[]
		{
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("lead", "Мәтін", FieldKind.Textarea),
			new FieldDef("facts", "Белгілер", FieldKind.List) { Fields = new[]
			{
				new FieldDef("icon", "Белгіше", FieldKind.Icon),
				new FieldDef("title", "Тақырып", FieldKind.Text),
				new FieldDef("text", "Жазу", FieldKind.Text)
			} },
			new FieldDef("ctaChoose", "Негізгі батырма", FieldKind.Text),
			new FieldDef("ctaCourse", "Курс батырмасы", FieldKind.Text),
			new FieldDef("ctaCourseService", "Курс батырмасы ашатын қызмет", FieldKind.Service),
			new FieldDef("ctaNote", "Батырма астындағы жазу", FieldKind.Text)
		}),
		new BlockDef("kaztest.law", "kaztest", "2026 жылғы талап туралы блок", null, new[]
		{
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("text", "Мәтін", FieldKind.Textarea),
			new FieldDef("sources", "Дереккөздер жолы", FieldKind.Html)
		}),
		new BlockDef("kaztest.list", "kaztest", "Нұсқалар бөлімі және тест баптаулары", "Сұрақтар мен нұсқалар «ҚАЗТЕСТ» мәзірінде. Уақыт пен өту шегі барлық нұсқаға ортақ.", new[]
		{
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("aside", "Оң жақтағы түсініктеме", FieldKind.Textarea),
			new FieldDef("note", "Тізім астындағы жазу", FieldKind.Textarea),
			new FieldDef("minutes", "Тест уақыты (минут)", FieldKind.Number),
			new FieldDef("passPercent", "Өту шегі, әр бөлімнен (%)", FieldKind.Number)
		}),
		new BlockDef("kaztest.how", "kaztest", "«Қалай өтеді»", null, new[]
		{
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("aside", "Оң жақтағы түсініктеме", FieldKind.Textarea),
			new FieldDef("steps", "Қадамдар", FieldKind.List) { Fields = new[]
			{
				new FieldDef("title", "Атауы", FieldKind.Text),
				new FieldDef("text", "Түсініктеме", FieldKind.Textarea)
			} }
		}),
		new BlockDef("kaztest.faq", "kaztest", "Сұрақ-жауап", null, new[]
		{
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("lead", "Түсініктеме", FieldKind.Text),
			new FieldDef("items", "Сұрақтар", FieldKind.List) { Fields = new[]
			{
				new FieldDef("q", "Сұрақ", FieldKind.Text),
				new FieldDef("a", "Жауап (HTML рұқсат)", FieldKind.Textarea)
			} }
		}),
		new BlockDef("kaztest.cross", "kaztest", "Төменгі шақыру жолағы", null, new[]
		{
			new FieldDef("image", "Фон суреті", FieldKind.Image),
			new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("text", "Мәтін", FieldKind.Textarea),
			new FieldDef("button", "Негізгі батырма («Кеңес алу» терезесін ашады)", FieldKind.Text),
			new FieldDef("serviceKey", "Терезеде таңдалып тұратын қызмет (бос болса — жалпы кеңес)", FieldKind.Service),
			new FieldDef("linkText", "Екінші батырма мәтіні", FieldKind.Text),
			new FieldDef("linkUrl", "Екінші батырма сілтемесі", FieldKind.Url)
		}),
	};

	/// <summary>Sections of a service detail page (servicepage.dataJson).</summary>
	public static readonly FieldDef[] ServicePageFields =
	{
		new FieldDef("eyebrow", "Үстіңгі жол", FieldKind.Text),
		new FieldDef("lead", "Кіріспе", FieldKind.Textarea),
		new FieldDef("crumbText", "Жолсілтемедегі бөлім атауы", FieldKind.Text),
		new FieldDef("crumbUrl", "Бөлім сілтемесі", FieldKind.Url),
		new FieldDef("cta", "Негізгі батырма", FieldKind.Text),
		new FieldDef("serviceKey", "Батырма ашатын қызмет", FieldKind.Service),
		new FieldDef("ctaNote", "Батырма астындағы жазу", FieldKind.Text),
		new FieldDef("keyfacts", "Негізгі сандар", FieldKind.List) { Fields = new[]
		{
			new FieldDef("value", "Мән", FieldKind.Text),
			new FieldDef("text", "Түсініктеме", FieldKind.Text)
		} },
		new FieldDef("benefitsEyebrow", "Артықшылықтар: үстіңгі жол", FieldKind.Text),
		new FieldDef("benefitsTitle", "Артықшылықтар: тақырып", FieldKind.Text),
		new FieldDef("benefitsLead", "Артықшылықтар: мәтін", FieldKind.Textarea),
		new FieldDef("benefits", "Артықшылықтар мен шектеулер", FieldKind.List) { Fields = new[]
		{
			new FieldDef("icon", "Белгіше", FieldKind.Icon),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("text", "Мәтін", FieldKind.Textarea),
			new FieldDef("negative", "Шектеу (қызыл)", FieldKind.Bool)
		} },
		new FieldDef("whoEyebrow", "«Кімге»: үстіңгі жол", FieldKind.Text),
		new FieldDef("whoTitle", "«Кімге»: тақырып", FieldKind.Text),
		new FieldDef("whoAside", "«Кімге»: түсініктеме", FieldKind.Textarea),
		new FieldDef("who", "Санаттар", FieldKind.List) { Fields = new[]
		{
			new FieldDef("label", "Белгі (мыс. 1-санат)", FieldKind.Text),
			new FieldDef("icon", "Белгіше", FieldKind.Icon),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("text", "Мәтін", FieldKind.Textarea)
		} },
		new FieldDef("stepsEyebrow", "Қадамдар: үстіңгі жол", FieldKind.Text),
		new FieldDef("stepsTitle", "Қадамдар: тақырып", FieldKind.Text),
		new FieldDef("stepsAside", "Қадамдар: түсініктеме", FieldKind.Textarea),
		new FieldDef("steps", "Қадамдар", FieldKind.List) { Fields = new[]
		{
			new FieldDef("title", "Атауы", FieldKind.Text),
			new FieldDef("text", "Мәтін", FieldKind.Textarea),
			new FieldDef("time", "Қысқа белгі", FieldKind.Text)
		} },
		new FieldDef("disclaimer", "Ескерту (қадамдар астында)", FieldKind.Textarea),
		new FieldDef("docsEyebrow", "Құжаттар: үстіңгі жол", FieldKind.Text),
		new FieldDef("docsTitle", "Құжаттар: тақырып", FieldKind.Text),
		new FieldDef("docsLead", "Құжаттар: түсініктеме", FieldKind.Textarea),
		new FieldDef("docs", "Құжаттар тізімі (келушінің белгілері өз құрылғысында сақталады)", FieldKind.List) { Fields = new[]
		{
			new FieldDef("title", "Құжат", FieldKind.Text),
			new FieldDef("note", "Түсініктеме", FieldKind.Text)
		} },
		new FieldDef("panelTitle", "Дайындық панелінің тақырыбы", FieldKind.Text),
		new FieldDef("tipTitle", "Кеңес: тақырып", FieldKind.Text),
		new FieldDef("tipText", "Кеңес: мәтін", FieldKind.Textarea),
		new FieldDef("tipLinkText", "Кеңес: сілтеме мәтіні", FieldKind.Text),
		new FieldDef("tipLinkUrl", "Кеңес: сілтеме", FieldKind.Url),
		new FieldDef("faqTitle", "Сұрақ-жауап тақырыбы", FieldKind.Text),
		new FieldDef("faq", "Сұрақтар", FieldKind.List) { Fields = new[]
		{
			new FieldDef("q", "Сұрақ", FieldKind.Text),
			new FieldDef("a", "Жауап (HTML рұқсат)", FieldKind.Textarea)
		} },
		new FieldDef("relatedEyebrow", "Ұқсас қызметтер: үстіңгі жол", FieldKind.Text),
		new FieldDef("relatedTitle", "Ұқсас қызметтер: тақырып", FieldKind.Text),
		new FieldDef("related", "Ұқсас қызметтер", FieldKind.List) { Fields = new[]
		{
			new FieldDef("kicker", "Белгі", FieldKind.Text),
			new FieldDef("title", "Тақырып", FieldKind.Text),
			new FieldDef("text", "Мәтін", FieldKind.Textarea),
			new FieldDef("url", "Сілтеме", FieldKind.Url)
		} }
	};
}
